extends Node2D

var choices := [
	{"key":"1", "title":"Crystal Dash", "scene":"res://scenes/CrystalDash.tscn", "desc":"20-second coin sprint. WASD/Arrows move."},
	{"key":"2", "title":"Meteor Umbrella", "scene":"res://scenes/MeteorUmbrella.tscn", "desc":"Dodge a procedural meteor rain as long as possible."},
	{"key":"3", "title":"Orbit Shooter", "scene":"res://scenes/OrbitShooter.tscn", "desc":"Arcade shooter: move, Space fires, pop orbs."},
]

func _ready() -> void:
	queue_redraw()

func _input(event: InputEvent) -> void:
	if event is InputEventKey and event.pressed and not event.echo:
		if event.keycode == KEY_1:
			get_tree().change_scene_to_file(choices[0].scene)
		elif event.keycode == KEY_2:
			get_tree().change_scene_to_file(choices[1].scene)
		elif event.keycode == KEY_3:
			get_tree().change_scene_to_file(choices[2].scene)
		elif event.keycode == KEY_ESCAPE:
			get_tree().quit()

func _draw() -> void:
	draw_rect(Rect2(Vector2.ZERO, Vector2(960, 540)), Color(0.015, 0.018, 0.04))
	for i in range(42):
		var x := fmod(float(i * 137), 960.0)
		var y := fmod(float(i * 251), 540.0)
		draw_circle(Vector2(x, y), 1.5 + float(i % 3), Color(0.18, 0.38, 0.8, 0.35))
	draw_string(ThemeDB.fallback_font, Vector2(70, 86), "HERMES GODOT PROTOTYPE PACK", HORIZONTAL_ALIGNMENT_LEFT, -1, 34, Color(0.4, 0.78, 1.0))
	draw_string(ThemeDB.fallback_font, Vector2(70, 126), "Three tiny playable scenes generated by Hermes. Press 1 / 2 / 3.", HORIZONTAL_ALIGNMENT_LEFT, -1, 18, Color(0.85, 0.9, 1.0))
	var y := 190.0
	for c in choices:
		draw_rect(Rect2(70, y - 34, 820, 76), Color(0.03, 0.07, 0.13, 0.9), true)
		draw_rect(Rect2(70, y - 34, 820, 76), Color(0.14, 0.42, 0.8, 0.85), false, 2)
		draw_string(ThemeDB.fallback_font, Vector2(96, y), c.key + ". " + c.title, HORIZONTAL_ALIGNMENT_LEFT, -1, 25, Color(1.0, 0.78, 0.28))
		draw_string(ThemeDB.fallback_font, Vector2(96, y + 28), c.desc, HORIZONTAL_ALIGNMENT_LEFT, -1, 16, Color(0.78, 0.86, 0.98))
		y += 98
	draw_string(ThemeDB.fallback_font, Vector2(70, 505), "Esc quits. In games: R restarts, Esc returns to menu.", HORIZONTAL_ALIGNMENT_LEFT, -1, 16, Color(0.65, 0.72, 0.86))
